language: python
python:
  - "3.6"
  - "3.7"
install:
  - pip install -r requirements.txt
  - pip install black flake8 mypy codecov pytest-cov pytest
script:
  - pytest --cov=pipecutter
after_success:
  - codecov